№3.1
- Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
- Считать данные с помощью pandas
- Вывести на экран первые 5 строк
- Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU (Intel, AMD и т.д)
- Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя (128, 1024, 256 и т.д.)
- Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD, SDD и т.д.)
- Удалите признаки Memory и ScreenResolution

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('laptop_price.csv', encoding='1251')

In [5]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,0
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,0

In [10]:
def vstavka(stroka):
    return stroka.split()[0]

In [11]:
df['Cpu_Company'] = df['Cpu'].apply(vstavka)

In [12]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

In [15]:
df['Cpu_Company'].value_counts()

Cpu_Company
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64

In [7]:
df[['Cpu_Company', 'Cpu']]

      Cpu_Company                                   Cpu
0               0                  Intel Core i5 2.3GHz
1               0                  Intel Core i5 1.8GHz
2               0            Intel Core i5 7200U 2.5GHz
3               0                  Intel Core i7 2.7GHz
4               0                  Intel Core i5 3.1GHz
...           ...                                   ...
1298            0            Intel Core i7 6500U 2.5GHz
1299            0            Intel Core i7 6500U 2.5GHz
1300            0  Intel Celeron Dual Core N3050 1.6GHz
1301            0            Intel Core i7 6500U 2.5GHz
1302            0  Intel Celeron Dual Core N3050 1.6GHz

[1303 rows x 2 columns]

In [ ]:
#Создать новый признак Memory_Amount, 
#который будет содержать только количество Gb памяти без указания типа носителя (128, 1024, 256 и т.д.)

In [35]:
def sumMem(stroka):
    return int(float(stroka.split()[0][:-2]))

In [39]:
df['Memory_Amount'] = df['Memory'].apply(sumMem)

In [40]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

In [38]:
df['Memory'].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [27]:
sumMem('256GB SSD +  1.0TB Hybrid')

256

In [28]:
sumMem('2TB HDD')

2

In [ ]:
#Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD, SDD и т.д.)

In [44]:
def typeMem(stroka1):
    return stroka1.split()[1]

In [46]:
df['Memory_Type'] = df['Memory'].apply(typeMem)

In [45]:
typeMem('256GB SSD +  1.0TB Hybrid')

'SSD'

In [47]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

In [48]:
df['Memory_Type'].value_counts()

Memory_Type
SSD       843
HDD       375
Flash      75
Hybrid     10
Name: count, dtype: int64

In [ ]:
#Удалите признаки Memory и ScreenResolution

In [51]:
df.drop(columns=['Memory', 'ScreenResolution'], inplace=True)

In [52]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

№3.2
- Создайте признак SSD, который изначально равен 0
- Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD
- Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [54]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

In [56]:
df.loc[df['Memory_Type'] == "SSD", 'SSD'] = 1

In [57]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1

№3.3
- Создайте датафрейм с клиентами:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
    laptop_id - это индексы датафрейма с ноутбуками
- Присоедините к таблице clients данные по ноутбукам через метод join
- Присоедините к таблице clients данные по ноутбукам через метод merge. Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [58]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})

In [60]:
clients_id = clients.set_index('laptop_id')

In [61]:
clients_id.join(df)

,client_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,,
506,45,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2kg,1224.0,Intel,256.0,SSD,1.0
398,32,405.0,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78kg,2712.0,Intel,256.0,SSD,1.0
710,67,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1249.0,Intel,128.0,SSD,1.0
120,33,123.0,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.1kg,479.0,Intel,1.0,HDD,0.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
merged = clients.merge(df, left_on='laptop_id', right_on=df.index, how='left')
merged

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,45,506,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2kg,1224.0,Intel,256.0,SSD,1.0
1,32,398,405.0,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78kg,2712.0,Intel,256.0,SSD,1.0
2,67,710,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1249.0,Intel,128.0,SSD,1.0
3,33,120,123.0,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.1kg,479.0,Intel,1.0,HDD,0.0
4,43,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

№3.4
Составьте несколько сводных таблиц
- Найдите среднюю стоимость ноутбуков в зависимости от компании производителя. Отсортируйте от меньшей стоимости к большей
- Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора
- Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [62]:
df.iloc[506]

laptop_ID                               513
Company                                Asus
Product              ZenBook UX510UX-CN211T
TypeName                           Notebook
Inches                                 15.6
Cpu              Intel Core i7 7500U 2.7GHz
Ram                                     8GB
Gpu                   Intel HD Graphics 620
OpSys                            Windows 10
Weight                                  2kg
Price_euros                          1224.0
Cpu_Company                           Intel
Memory_Amount                           256
Memory_Type                             SSD
SSD                                       1
Name: 506, dtype: object

№3.4
Составьте несколько сводных таблиц
- Найдите среднюю стоимость ноутбуков в зависимости от компании производителя. Отсортируйте от меньшей стоимости к большей
- Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора
- Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [71]:
df.pivot_table(index='Company', values='Price_euros', aggfunc='mean').sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

In [72]:
df.pivot_table(index='Company', values='Price_euros', aggfunc=[min, max])

                  min         max
          Price_euros Price_euros
Company
Acer           174.00     2599.00
Apple          898.94     2858.00
Asus           191.90     3975.00
Chuwi          244.99      449.00
Dell           274.90     3659.40
Fujitsu        649.00      799.00
Google        1275.00     2199.00
HP             209.00     4389.00
Huawei        1349.00     1499.00
LG            1899.00     2299.00
Lenovo         229.00     4899.00
MSI            839.00     2799.00
Mediacom       239.00      389.00
Microsoft      989.00     2589.00
Razer         1029.00     6099.00
Samsung        269.00     1849.00
Toshiba        447.00     2799.00
Vero           196.00      260.00
Xiaomi         935.00     1399.95

In [77]:
import numpy as np
df.pivot_table(index='Cpu_Company', values='Price_euros', aggfunc=['mean', 'max', 'min'])

                    mean         max         min
             Price_euros Price_euros Price_euros
Cpu_Company
AMD           560.638871      2199.0       199.0
Intel        1152.214145      6099.0       174.0
Samsung       659.000000       659.0       659.0

In [76]:
df.groupby('Cpu_Company').agg({'Price_euros': ['mean', 'max', 'min']})

             Price_euros
                    mean     max    min
Cpu_Company
AMD           560.638871  2199.0  199.0
Intel        1152.214145  6099.0  174.0
Samsung       659.000000   659.0  659.0


№3.5
Ответьте на несколько вопросов, используя методы группировки
- Ноутбуков каких компаний и с каким процессором больше?
- С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [78]:
pd.crosstab(index=df['Company'], columns=df['Cpu_Company'])

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

In [81]:
pd.crosstab(index=df['Company'], columns=df['Cpu_Company'], normalize='columns')

Cpu_Company       AMD     Intel  Samsung
Company
Acer         0.161290  0.075000      0.0
Apple        0.000000  0.016935      0.0
Asus         0.177419  0.118548      0.0
Chuwi        0.000000  0.002419      0.0
Dell         0.000000  0.239516      0.0
Fujitsu      0.000000  0.002419      0.0
Google       0.000000  0.002419      0.0
HP           0.403226  0.200806      0.0
Huawei       0.000000  0.001613      0.0
LG           0.000000  0.002419      0.0
Lenovo       0.258065  0.226613      0.0
MSI          0.000000  0.043548      0.0
Mediacom     0.000000  0.005645      0.0
Microsoft    0.000000  0.004839      0.0
Razer        0.000000  0.005645      0.0
Samsung      0.000000  0.006452      1.0
Toshiba      0.000000  0.038710      0.0
Vero         0.000000  0.003226      0.0
Xiaomi       0.000000  0.003226      0.0